# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: deb4sh Notebook
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  a short and simple notebook of a platform engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  deB4SH

# Build settings
theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

read_time: true
words_per_minute: 200

date_format: "%B %-d, %Y"

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Site Author
author:
  name: deB4SH
  picture: /images/authors/img.png
  email: ""
  twitter: ""
  links:
    - title: Mastodon
      url: https://hachyderm.io/@deb4sh
      icon: fab fa-mastodon 
    - title: GitHub
      url: https://github.com/deb4sh
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Mastodon
    url: https://hachyderm.io/@deb4sh
    icon: fab fa-mastodon 
  - title: GitHub
    url: https://github.com/deb4sh
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
