title: deb4sh Notebook
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  a short and simple notebook of a platform engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  deB4SH

# Build settings
theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

read_time: true
words_per_minute: 200

date_format: "%B %-d, %Y"

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Site Author
author:
  name: deB4SH
  picture: /images/authors/img.png
  email: ""
  twitter: ""
  links:
    - title: Mastodon
      url: https://hachyderm.io/@deb4sh
      icon: fab fa-mastodon 
    - title: GitHub
      url: https://github.com/deb4sh
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Mastodon
    url: https://hachyderm.io/@deb4sh
    icon: fab fa-mastodon 
  - title: GitHub
    url: https://github.com/deb4sh
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
